## Assignment  Numpy

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np

In [2]:
def Vandermonde(ip_vector,N,increasing=False):
    '''
    ip_vector => input vector
    N=> Total no of column required in op matrix
    increasing=>True if order of power increasing and False if order of power is decreasing
    '''
    if increasing==False:
        op_mat = np.array([x**(N-i-1)for x in ip_vector for i in range(N)]).reshape(ip_vector.size,N)
    elif increasing==True:
        op_mat = np.array([x**i for x in ip_vector for i in range(N)]).reshape(ip_vector.size,N)
    return op_mat

In [3]:
#increasing => False
ip_vector = np.array([10,20,30,40])
N=4
Vandermonde(ip_vector,N)

array([[ 1000,   100,    10,     1],
       [ 8000,   400,    20,     1],
       [27000,   900,    30,     1],
       [64000,  1600,    40,     1]])

In [4]:
#increasing =>True
ip_vector = np.array([10,20,30,40])
N=4
Vandermonde(ip_vector,N,increasing = True)

array([[    1,    10,   100,  1000],
       [    1,    20,   400,  8000],
       [    1,    30,   900, 27000],
       [    1,    40,  1600, 64000]])

-------------------------------------------------------------------------------------------------------------------------------

Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
def moving_avg(list,k):
    '''
    moving_avg is a function to find moving average in an array over a window(k)
    
    list = list of input numbers
    k = window
    returns output of moving average in an array over a window(k)
    '''
    n=len(list)
    op=[]
    for i in range(n-k+1):
            res= np.mean(list[i:i+k])
            op.append(res)
    return np.array(op)

In [6]:
#Testing Function 
l=[10,20,30,40,50,60,70,80,90,100]
k=4
moving_avg(l,k)

array([25., 35., 45., 55., 65., 75., 85.])

In [7]:
k=3
moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],k)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])